### ISSUE TITLE
Events fired by contracts during ContractAddressChange

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#10]
https://github.com/orbs-network/orbs-ethereum-contracts-v2/blob/446cdecb3a54e78169141f7112f09835814c75f5/contracts/spec_interfaces/IContractRegistry.sol#L5

ManagementReader and other clients need to know when to start observing events from the new contract and stop observing events from the old one.

We can assume that from the block height of the `ContractAddressChange` event onward we should observe the new contract. But we need to defined the edge cases. 
- what happens when there are events from both contracts in question (retired and new) emitted in the same block number as `ContractAddressChange`?
- what happens when there are events emitted recently by the new contract - but prior to `ContractAddressChange` - do we acknowledge them or not?
- what happens when there are events emitted shortly after `ContractAddressChange` by the retired contract. do we acknowledge them?

@amir-arad suggested specifying the exact block number from which to listen events emitted from the contract referenced by `addr` in the address change event - but this may be an overkill and also to be exhaustive of all possibilities may require also adding a block number from which to stop observing events from the retired contract. again, sounds like an overkill.

please clarify

**Comment by vistra** [comment]
AFAIK - we only consider events emitter after the `ContractAddressChange` event. Even if in the same block, they are ordered, so that's not an issue.

**Comment by OdedWx** [comment]
Consider locking a managed contract that is removed from the registry

**Comment by OdedWx** [comment]
* A contract may emit an event before or after connecting to the registry.
* The events that are considered are the ones of a the registered contract
* Event ordering may be achieved by {block, log_index}
* There is an issue with the configuration of a new contract, may be addressed by emitting a configuration change for all parameters upon connecting to the registry

**Comment by OdedWx** [comment]
Consider a naming convention for settingsEvent: Setting<XXX>Changed to allow external tools to track them prior to when they were connected to the registry

**Comment by vistra** [comment]
Decided to assume that no events are emitted in the same block as the registry set transaction.
