### ISSUE TITLE
REWARDS - add explanation for no overflow in uint48

### ISSUE THREAD

**Issue by vistra** [orbs-network/orbs-ethereum-contracts-v2#170]
Document the assumptions that allow us to consider raw addition as safe (e.g. limited amount of ORBS)

_Originally posted by @vistra in https://github.com/orbs-network/orbs-ethereum-contracts-v2/pull/162/review_comment/create_

**Comment by OdedWx** [comment]
Orig name: REWARDS: The assumption that allows us to consider this as safe is used in many places across the contract. Need to find a way to make this clearer. Opening an issue.

**Comment by OdedWx** [comment]
TODO SafeMath variation
