### ISSUE TITLE
Change "Member" in ICommittee

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#30]
the word member does not describe a member of the topology or the committee. i feel it's inappropriate and should change to "Validator" or something similar (eligibleValidator, trackedValidator, etc).

---

also, internally there is a question of the naming of `participants` array and transient struct. see discussion here:
https://github.com/orbs-network/orbs-ethereum-contracts-v2/pull/26#discussion_r419176822

suggest to change function names:
`qualifiedToJoinCommittee` -> `qualifiesToJoinCommittee`
`qualifiedToJoin` -> `qualifiesToParticipate`

**Comment by OdedWx** [comment]
participants changed to committee
change member to guardian
