### ISSUE TITLE
Constants library for contract names

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#31]
Share contract name constant definitions using a shared library 

is there an easy way to share constants by more than one contract? we probably should not do it by cross contract calls (getters/public constant vars) for gas reasons. but a library might do the trick?...

_Originally posted by @ronnno in https://github.com/orbs-network/orbs-ethereum-contracts-v2/pull/29_

**Comment by vistra** [comment]
The contract names are only used in one contract - `ContractRegistryAccessor`. Are there any other shared constants?

**Comment by OdedWx** [comment]
on hold
