### ISSUE TITLE
Remove standbys with stale RTS timestamp from participants list

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#34]
See discussion in link below:

_Originally posted by @ronnno in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDA0NjU5OTY3/pull_request_reviews/more_threads_

**Comment by vistra** [comment]
The link doesn't work for me but I think we decided to keep them in?

**Comment by OdedWx** [comment]
Not relevant - Standby management moved from the contract to the node services.
