### ISSUE TITLE
[REWARDS] Easy events to know delegator stake on changes for rewards distributor

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#43]
The rewards distributor needs to know for a specific guardian the staked amount per delegator at any given time.

Currently, the only way to get the staked amount per delegator is to synchronize over **all** events of the staking (locking) contract. We can't even apply filters here. This is a bit overkill for a browser-based tool.

Ideally, we could avoid going over the staking contract altogether by slightly changing this event:

`Delegation.DelegatedStakeChanged`

Currently, it only includes the new total for the guardian. What if we also included the delegator that caused this change and their total stake.

I would then also merge `Delegation.Delegated` into `Delegation.DelegatedStakeChanged` since it's a bit redundant. I can know about all the delegator addresses since they're reported in `Delegation.DelegatedStakeChanged`.

This will allow the rewards distributor to only sync over `Delegation.DelegatedStakeChanged` events and a filter can be applied too so only events relevant to the guardian doing the distribution can be taken, which is very nice for something that we need to do from the beginning of history.

**Comment by talkol** [comment]
Just to explain the proposal.. Here are a few scenarios:

## Scenario A - Tal started delegating (new delegator joined), delegating to G1

Emit `Delegation.DelegatedStakeChanged` with: G1 address, G1 new total stake, Tal address, Tal total stake as a positive number

## Scenario B - Tal switches from G1 to G2

Emit `Delegation.DelegatedStakeChanged` with: G1 address, G1 new total stake, Tal address, Tal total stake as a negative number

Emit `Delegation.DelegatedStakeChanged` with: G2 address, G2 new total stake, Tal address, Tal total stake as a positive number

## Scenario C - Tal stakes more tokens while delegated to G2

Emit `Delegation.DelegatedStakeChanged` with: G2 address, G2 new total stake, Tal address, Tal total stake as a positive number

**Comment by OdedWx** [comment]
I like the approach, but there is a contradiction in Tal's total field. 
* If it describes Tal current total stake then the negative value in B makes less sense.
* If it describes how much Tal delegates to the Delegate then in B it should be 0.
* If it describes the change in Tal's delegation to the Delegate then C should be the amount staked (the diff)

**Comment by talkol** [comment]
You're right, in B Tal's total stake should be zero. That's better.

**Comment by OdedWx** [comment]
Looks good to me. @ronnno @vistra , what do you think? 
* Adding address delegator, uint256 delegatorContribution to DelegatedStakeChanged
* Set addr and delegator as indexed

As all the data is available in the event, we can consider removing Delegated(address from, address to);

**Comment by OdedWx** [comment]
Proposal:
// Delegate view (+batch)
event DelegatedStakeChanged(address indexed addr, uint256 selfSstake, uint256 delegatedStake, address[] delegators, uint256[] delegatorAmounts, uint256[] delegatorTotalStakes);

// Delegator view
event Delegated(address indexed from, address indexed to);

Notes: 
* DelegatedStakeChanged events are indexed ONLY by the delegate (Guardian) not by the delegator (array)
* Single event format that supports batch (for reward distribution).
* Separation to multiple events is possible with a cost of ~1000 Gas per delegator. 
* if needed can add delegatorTotalStake to Delegated

**Comment by OdedWx** [comment]
event DelegatedStakeChanged(address indexed addr, uint256 selfSstake, uint256 delegatedStake, address[] delegators, uint256[] delegatorTotalStakes);

**Comment by OdedWx** [comment]
On delegation change emit 2 events one for each delegate with the leaving delegator.

**Comment by ronnno** [comment]
@OdedWx in `DelegatedStakeChanged ` I take `selfStake` to be the total stake balance of the delegator, regardless of if he delegates to himself or to someone else.
 
So currently I'm also adding the delegate to the arrays - otherwise the information about his self delegation is missing, i think. it would be more gas efficient to add a boolean and exclude the delegate from the delegator arrays always. but `selfStake` can also be taken to mean "self delegated stake" in which case I should truncate it to 0 if there is delegation to another, and we can avoid the boolean as well.

please clarify

**Comment by OdedWx** [comment]
It's a good point, in a sense it's misleading.  Let's change the name to selfDelegation.
If self delegating then selfDelegation = selfStake else 0.

@talkol , please see that it works for the rewards distributer.

**Comment by ronnno** [comment]
renaming  `selfStake` to `selfDelegatedStake`.  it will be 0 if the delegate has delegated his own stake away.
`delegatedStake` will always include this amount.

**Comment by talkol** [comment]
My only request is that when self delegation changes, it will appear in the `address[] delegators` array just like a regular delegator.

Since this is the current behavior, for me it's the easiest to integrate.

The reward distributor doesn't look at any of the other fields like `selfDelegatedStake` or `delegatedStake`, so I don't mind what you choose for them.
