### ISSUE TITLE
[BUG] DelegatedStakeChanged on delegator leaving does not report zero stake

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#57]
### Scenario:

1. D1 stakes 100
2. D1 delegates to V1
3. D1 delegates to V2

### Expected events:

After step 2:

DelegatedStakeChanged(addr V1, delegators [D1], delegatorTotalStakes [100])

After step 3:

DelegatedStakeChanged(addr V1, delegators [D1], delegatorTotalStakes [0])
DelegatedStakeChanged(addr V2, delegators [D1], delegatorTotalStakes [100])

### Actual events:

After step 2:

DelegatedStakeChanged(addr V1, delegators [D1], delegatorTotalStakes [100])

After step 3:

**DelegatedStakeChanged(addr V1, delegators [D1], delegatorTotalStakes [100]) <--**
DelegatedStakeChanged(addr V2, delegators [D1], delegatorTotalStakes [100])

**Comment by talkol** [comment]
The zero issue was discussed here:

https://github.com/orbs-network/orbs-ethereum-contracts-v2/issues/43#issuecomment-624797904

Not sure if we decided to change it back :)

**Comment by ronnno** [comment]
Correct. Will be fixed in v0.0.6
