### ISSUE TITLE
[BUG] DelegatedStakeChanged reported with delegator as addr

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#58]
## Scenario:

D4 is a delegator only, created with the testkit this way:

```js
const d4 = d.newParticipant();
await d4.stake(400000);
await d4.delegate(v2);
```

I see DelegatedStakeChanged events emitted with D4 as the `addr`:

```
{
    '0': '0x6766d79E`81F592acFc9de4B810161929aB9E3',
    '1': '0',
    '2': '0',
    '3': [ '0x6766d79E08681F592acFc9de4B810161929aB9E3' ],
    '4': [ '400000' ],
    addr: '0x6766d79E08681F592acFc9de4B810161929aB9E3',
    selfDelegatedStake: '0',
    delegatedStake: '0',
    delegators: [ '0x6766d79E08681F592acFc9de4B810161929aB9E3' ],
    delegatorTotalStakes: [ '400000' ]
}
```

I expected the `addr` argument only to have validators.

If it doesn't, we report many redundant events since every delegator in the system will have these events reported, yet they're not validators, can't distribute rewards and this event is primarily for the rewards distributor.

**Comment by vistra** [comment]
Theoretically validators can become validators and vice versa, so maybe it's better to keep these for completeness? Gas-wise it's negligible.

**Comment by talkol** [comment]
Good point. If we remove those, we have a new edge case of when a delegator registers as validator, we would need to output the DelegatedStakeChanged in this case.

I hit this issue when I tried to do network analytics and collect information on all guardians and I accidentally started showing info on all members of the network, delegators included. Maybe I should base who I show in the analytics on who received an assignment. Addresses who never received an assignment are not interesting to analyze. What do you think?

**Comment by vistra** [comment]
Sounds good, or you can filter by addresses that appeared in CommitteeChanged events.

**Comment by vistra** [comment]
(to cover the edge case of a validated who has yet to be assigned with rewards)

**Comment by talkol** [comment]
You're right, committee is better since if I see an assignment I must always see in committee. But the opposite isn't true.

Ok - so we're decided - I'm basing the analytics of guardians on who ever appeared at least once in the committee.

**Comment by talkol** [comment]
Keeping this as intended behavior, no need to fix.
