### ISSUE TITLE
[BUG] Calling distributeOrbsTokenRewards twice with same txIndex

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#59]
I have 5000 ORBS to distribute in the balance.
Distribution tx1 has total of 3000.
Distribution tx2 has total of 2000.

I'm sending tx1 twice (with the same txIndex 0) but the failure I'm getting is this:

```
Error: Returned error: VM Exception while processing transaction: revert not enough balance for this distribution
```

5000 - 3000 - 3000 < 0

But I'm expecting to fail on an error that I'm using an old txIndex.

**Comment by vistra** [comment]
There are two problems with this tx: one is the balance, the other is the tx index. It should check for both. Assuming it does, why does the order matter?
(if you did 2000 in tx1, I believe it should have filed the old txIndex error)

**Comment by talkol** [comment]
If changing the order of the checks is easy, I think it's better to change. Since one error is indicative of the real problem and the second error is misleading.

I debugged the entire logic of the balance calculation because I was sure my code makes a mistake and tries to distribute more balance than what it has :)

**Comment by vistra** [comment]
Right, that makes sense. Will change.
