### ISSUE TITLE
Protocol Upgrade scheduled at least 1 hour forward

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#88]
see [spec](https://docs.google.com/document/d/1-G5ZKpmoIPsiC-yxvgYpc6ZDOm4zIkJB94QXUVOgg-Y/edit#heading=h.s0cle83js675):

>  a protocol event can’t be triggered an hour prior to the pending one timestamp.

**Comment by OdedWx** [comment]
on hold
